### ISSUE TITLE
AttributeError while running demo

### ISSUE THREAD

**Issue by mepwang** [happydasch/btconfig#6]
OS: Ubuntu 21.04
Python: 3.9.6
backtrader: origin/master
btconfig: origin/master

python run_backtest.py

Traceback (most recent call last):
  File "/home/mep/trade/pyht/btconfig/demo/simple/run_backtest.py", line 16, in <module>
    res = btconfig.run(btconfig.MODE_BACKTEST, "config.json")
  File "/home/mep/trade/pyht/env/lib/python3.9/site-packages/btconfig-0.2.0-py3.9.egg/btconfig/__init__.py", line 721, in run
  File "/home/mep/trade/pyht/env/lib/python3.9/site-packages/btconfig-0.2.0-py3.9.egg/btconfig/__init__.py", line 479, in run
  File "/home/mep/trade/pyht/env/lib/python3.9/site-packages/btconfig-0.2.0-py3.9.egg/btconfig/__init__.py", line 356, in _loadParts
  File "/home/mep/trade/pyht/env/lib/python3.9/site-packages/btconfig-0.2.0-py3.9.egg/btconfig/helper.py", line 153, in get_classes
  File "/home/mep/trade/pyht/env/lib/python3.9/site-packages/btconfig-0.2.0-py3.9.egg/btconfig/helper.py", line 123, in _iter_classes_submodules
  File "/home/mep/trade/pyht/env/lib/python3.9/site-packages/btconfig-0.2.0-py3.9.egg/btconfig/helper.py", line 138, in _import_module
AttributeError: 'zipimporter' object has no attribute 'exec_module'

pip list
Package            Version
------------------ -----------------------
backcall           0.2.0
backtrader         1.9.76.123
beautifulsoup4     4.9.3
bs4                0.0.1
btconfig           0.2.0
certifi            2021.5.30
chardet            4.0.0
charset-normalizer 2.0.3
click              8.0.1
cycler             0.10.0
debugpy            1.3.0
decorator          5.0.9
empyrical          0.5.5
IbPy2              0.8.0
idna               2.10
ipykernel          6.0.3
ipython            7.25.0
ipython-genutils   0.2.0
jedi               0.18.0
joblib             1.0.1
jupyter-client     6.2.0
jupyter-core       4.7.1
kiwisolver         1.3.1
lxml               4.6.3
matplotlib         3.4.2
matplotlib-inline  0.1.2
multitasking       0.0.9
nest-asyncio       1.5.1
nltk               3.6.2
numpy              1.21.1
pandas             1.3.0
pandas-datareader  0.10.0
parso              0.8.2
pexpect            4.8.0
pickleshare        0.7.5
Pillow             8.3.1
pip                21.1.3
pkg-resources      0.0.0
prompt-toolkit     3.0.19
ptyprocess         0.7.0
pyfolio            0.9.2+75.g4b901f6.dirty
Pygments           2.9.0
pyparsing          2.4.7
python-dateutil    2.8.2
pytz               2021.1
pyzmq              22.1.0
QuantStats         0.0.34
regex              2021.7.6
requests           2.26.0
scikit-learn       0.24.2
scipy              1.7.0
seaborn            0.11.1
setuptools         57.4.0
simplejson         3.17.3
six                1.16.0
soupsieve          2.2.1
TA-Lib             0.4.21
tabulate           0.8.9
threadpoolctl      2.2.0
torch              1.9.0
tornado            6.1
tqdm               4.61.2
traitlets          5.0.5
tushare            1.2.64
typing-extensions  3.10.0.0
urllib3            1.26.6
wcwidth            0.2.5
websocket-client   1.1.0
yfinance           0.1.63

please help here.

**Comment by mepwang** [comment]
a 'circular import' problem?

**Comment by mepwang** [comment]
to resolve the error, add the following code:

```
from zipimport import zipimporter

def create_module(self, spec):
    return None
zipimporter.create_module = create_module

def exec_module(self, module):
    exec(self.get_code(module.__name__), module.__dict__)
zipimporter.exec_module = exec_module
```

**Comment by happydasch** [comment]
Could you provide some code to reproduce this issue?

**Comment by mepwang** [comment]
> Could you provide some code to reproduce this issue?

virtualenv for python
---
python -m venv env
source env/bin/activate
git clone https://github.com/happydasch/btconfig.git
cd btconfig

install package
---
pip install -r requirements.txt
python setup.py install             <========this leads to an egg installation, which results to a zipimporter
cd demo/simple
python run_backtest.py

**Comment by happydasch** [comment]
Thanks for this issue. Fixed with latest commit.
