### ISSUE TITLE
plotting default port

### ISSUE THREAD

**Issue by mepwang** [happydasch/btconfig#7]
the plotting default port is 80, which requires extra privilege, please set to 8080

**Comment by happydasch** [comment]
btconfig is using the default http port, you can override the port by providing a port=8080 in your config.

for example like this:
```
    "plot": {
        "use": "web",
        "style": "candle",
        "port": 80,
        "live_lookback": 50
    }
```

**Comment by mepwang** [comment]
port setting not working for optimize run, since in btconfig/parts/plot.py,  line 115: 

```
        browser = BacktraderPlottingOptBrowser(
            self.btplotting,
            result,
            usercolumns={'Profit & Loss': _analyzer_df},
            sortcolumn='Profit & Loss',
            sortasc=False)
```

missing port parameter

**Comment by happydasch** [comment]
I do not see any issue on the commented line. The port is being set on line 110 in plot.py

**Comment by happydasch** [comment]
I see now what the issue is, will reopen and fix that
